### ISSUE TITLE
[improvement] game system

### ISSUE THREAD

**Issue by mote166** [Matze997/Football#1]
make it have its own game system, a min players/maxplayers setting, a join/quit command, a countdown until start, a count down when the game starts which lasts 5 minutes, and scores as popup, and when a team scores all players respawn in thier positions and add sounds to the game.
* so to order them correctly here's an example:

to make a game we first set the game level, the min players and max players for each team with ``/fb setminplayers {number}`` and ``/fb setmaxplayers {number}`` (min players is for each team so if min players is 2 and a team has 2 players and the other one has 1 player the game doesn't start), then we do ``/fb setspawn {team} {spawn number}``, and we set where the ball will spawn with ``/fb setballspawn``, and we set the max score count with ``/fb setmaxscore {number}``, and after setting the teams spawns we join the game with ``/fb join`` or ``/fb join {arena name}`` if you are going to make it have multi arena support, or just ``/fb join`` and i lets u join the free arena directly,
and when we join first player goes to a team and the second player goes to the opposite team and so on, so we don't have 1 full team and the other one has 1 player, and when the min players are there (team1 equals to team2 and is not 0) a count down of 10 seconds start and after it finishes the game starts, then a popup with the game status shows up to both teams so they can see how many scores they made, and when the ball hits the cobweb aka the gate, it counts it as a goal and it says who was the last player who touched it in a title, then the ball despawns and respawns in its position and players respawn to thier positions and go immune so they don't move, then a count down of 3 seconds starts and after it finishes the players may move again to try and score, once the the score reaches the max score we set or the time runs out the team with the most score count wins and they teleport back to the main world.

yeah forgot to mention that when the player joins a team he should have a colored armor so the other players know who are with them and who aren't, so i suggest the teams be red and green. also no need for world reset ;)

**Comment by Matze997** [comment]
Hey,
I really like your idea!
It will come defenetly :-D

**Comment by mote166** [comment]
looking forward to test it 👍

**Comment by Smorted** [comment]
what happened to this idea?

**Comment by 333BlackCat333** [comment]
Hi on the version of pocketmine 1.16.0 the skin disappears, but I have already updated to 1.16.20 and 1.14. x on it everything is fine with the skin of the ball. The plugin is super!
--
Отправлено из Mail.ru для Android вторник, 01 сентября 2020г., 20:56 +05:00 от Smorted  notifications@github.com :

**Comment by Matze997** [comment]
Hey 333BlackCat333,
thanks for using my plugin!😁
Have you enabled "Not-Trusted-Skins"?

**Comment by Smorted** [comment]
@333BlackCat333 works fine for me, did you turn off trusted skins in mcpe settings?
