### ISSUE TITLE
Skin

### ISSUE THREAD

**Issue by Matze997** [Matze997/Football#3]
Hey 333BlackCat333,
thanks for using my plugin!😁
Have you enabled "Not-Trusted-Skins"?

**Comment by 333BlackCat333** [comment]
Where is the "Not-Trusted-Skins" function located? And thank you for creating this plugin!
--
Отправлено из Mail.ru для Android вторник, 01 сентября 2020г., 21:19 +05:00 от Matze  notifications@github.com :

**Comment by Matze997** [comment]
Hey,
it's a setting in the profile tab!
And thanks for your feedback.

333BlackCat333 <notifications@github.com> schrieb am Di., 1. Sep. 2020,
18:22:

**Comment by 333BlackCat333** [comment]
Found! Many thanks 😉
--
Отправлено из Mail.ru для Android вторник, 01 сентября 2020г., 21:25 +05:00 от Matze  notifications@github.com :
