### ISSUE TITLE
ball colliding with blocks

### ISSUE THREAD

**Issue by Smorted** [Matze997/Football#5]
when u push the ball beside a wall and make it so close to it half of the ball gets inside the block, and when u reach a corner the ball is stuck 
![Screenshot_20200916_074158](https://user-images.githubusercontent.com/69832226/93293339-652ed080-f7f0-11ea-88ba-ecad5f9a65c5.jpg)

in this picture the ball was stuck in the corner and no matter how much the player tries to get it out of there it just bounces up (in the Y coord) while staying in that same corner (x and z don't change)

**Comment by Smorted** [comment]
another example which shows that half of the ball is inside the block

![Screenshot_20200903_040855_com mojang minecraftpe](https://user-images.githubusercontent.com/69832226/93293645-22b9c380-f7f1-11ea-80e5-fd4a440b9fb4.jpg)

**Comment by Matze997** [comment]
Hey @Smorted,
this issue is known, but I`m not quite sure how to fix it.
But I will take another look over the code! :-D

~Matze

**Comment by Smorted** [comment]
maybe it has something to do with the ball's width because when i made it higher it didnt go inside the blocks but now when colliding with a player the ball is kicked before the player gets near it

**Comment by Smorted** [comment]
maybe u can edit its colliding box or something
