### ISSUE TITLE
Odd Protocol Issue

### ISSUE THREAD

**Issue by KadTheHunter** [Matze997/Football#6]
When I try and load the plugin, it says this:
`[17:51:06] [Server thread/ERROR]: Could not load plugin 'Football': Incompatible network protocol version (plugin requires one of: 407)`

Yet I see in plugin.yml that it's **already** protocol 407.
Tried using release and dev builds, same issue.

**Comment by Matze997** [comment]
Hey, this issue should be fixed.
Here is the new version:
https://poggit.pmmp.io/p/Football/1.2.1
