### ISSUE TITLE
About Spawning/Adding Gates

### ISSUE THREAD

**Issue by KadTheHunter** [Matze997/Football#7]
When I run `/football addgate` it says the first position is set. What other commands do I need to run after that, because each time I run that I get the same message, and in /football I can't see any other commands beyond addgate/removegate spawn/remove.

**Comment by Matze997** [comment]
Hey,
after running the command you have to break the block which should be the
first position. And do the same to all the other messages you get from the
plugin which says "You have to set a position".

Need more help? Write me on Discord or GitHun

~Matze

KadTheHunter <notifications@github.com> schrieb am Mo., 21. Sep. 2020,
17:41:

**Comment by KadTheHunter** [comment]
Ah ok thank you.
