### ISSUE TITLE
Incompatible network protocol 408 

### ISSUE THREAD

**Issue by UnEnanoMas** [Matze997/Football#8]
[02:14:21] [Server thread/ERROR]: Could not load plugin 'Football': Incompatible network protocol version (plugin requires one of: 408)

**Comment by KadTheHunter** [comment]
Dev just needs to add Protocol 419 into the list I think. If it's necessary for your server, you can just fork it, make that simple change and make it a dev build on Poggit.

**Comment by KadTheHunter** [comment]
aaand now it needs Protocol 422. I'll PR it in a minute.
